/**
 * ════════════════════════════════════════════════════════════════════════════════
 * 🤖 AI REPORT CARD COMPONENT - AI ANALYSIS DISPLAY
 * ════════════════════════════════════════════════════════════════════════════════
 * 
 * PURPOSE:
 * --------
 * This component displays the AI's analysis of a candidate's video screening.
 * It's the "report card" that summarizes AI scores, recommendations, strengths,
 * and concerns in a beautiful, easy-to-read format.
 * 
 * WHERE IT'S USED:
 * ----------------
 * - Embedded in VideoScreeningDetailView.tsx (right sidebar)
 * - Could also be used in dashboard cards (summary view)
 * - Reusable component (can be used anywhere AI results needed)
 * 
 * WHAT IT SHOWS:
 * --------------
 * ✅ Overall Score (0-100) with letter grade (A+, A, B, C, D, F)
 * ✅ Score Breakdown (Content, Communication, Technical)
 * ✅ AI Recommendation Badge (Invite/Review/Reject)
 * ✅ AI Summary (paragraph explaining assessment)
 * ✅ Key Strengths (bullet list)
 * ✅ Areas of Concern (bullet list)
 * ✅ Disclaimer (AI is a tool, not replacement)
 * 
 * VISUAL LAYOUT:
 * --------------
 * ┌───────────────────────────────────────┐
 * │ 🤖 AI Analysis Report                 │
 * │ Generated by RecruitPro SA AI engine  │
 * ├───────────────────────────────────────┤
 * │                                       │
 * │         Overall Assessment            │
 * │              ┌─────┐                  │
 * │              │  85 │                  │
 * │              │  A  │                  │
 * │              └─────┘                  │
 * │            out of 100                 │
 * │                                       │
 * │ Score Breakdown                       │
 * │ Content Quality      [━━━━━━━━  ] 80 │
 * │ Communication Skills [━━━━━━━━━━] 90 │
 * │ Technical Depth      [━━━━━━━━  ] 85 │
 * │                                       │
 * │ ┌───────────────────────────────────┐ │
 * │ │ ✅ Strongly Recommend             │ │
 * │ │ Candidate shows strong potential  │ │
 * │ └───────────────────────────────────┘ │
 * │                                       │
 * │ 📝 AI Summary                         │
 * │ Strong candidate with excellent...    │
 * │                                       │
 * │ ✅ Key Strengths                      │
 * │ ✓ Excellent communication skills      │
 * │ ✓ Deep technical knowledge            │
 * │                                       │
 * │ ⚠️ Areas of Concern                   │
 * │ ⚠ Limited team leadership experience  │
 * │                                       │
 * │ Note: AI analysis is a tool...        │
 * └───────────────────────────────────────┘
 * 
 * PROPS INTERFACE:
 * ----------------
 * interface AIReportCardProps {
 *   overallScore: number;            // 0-100
 *   contentScore: number;            // 0-100
 *   communicationScore: number;      // 0-100
 *   technicalScore: number;          // 0-100
 *   aiSummary: string;               // Paragraph text
 *   recommendation: 'invite_to_interview' | 'further_review' | 'reject';
 *   strengths: string[];             // Array of strength statements
 *   concerns: string[];              // Array of concern statements
 * }
 * 
 * USAGE EXAMPLE:
 * --------------
 * <AIReportCard
 *   overallScore={85}
 *   contentScore={80}
 *   communicationScore={90}
 *   technicalScore={85}
 *   aiSummary="Strong candidate with excellent communication..."
 *   recommendation="invite_to_interview"
 *   strengths={[
 *     "Excellent communication skills",
 *     "Deep technical knowledge of Python"
 *   ]}
 *   concerns={[
 *     "Limited team leadership experience"
 *   ]}
 * />
 * 
 * LETTER GRADE CALCULATION:
 * -------------------------
 * 90-100 → A+ (Exceptional)
 * 80-89  → A  (Excellent)
 * 70-79  → B  (Good)
 * 60-69  → C  (Satisfactory)
 * 50-59  → D  (Below Average)
 * 0-49   → F  (Poor)
 * 
 * SCORE COLOR CODING:
 * -------------------
 * 🟢 Green (80-100)  → Strong performance
 * 🟡 Yellow (60-79)  → Mixed performance
 * 🔴 Red (0-59)      → Weak performance
 * 
 * Applies to:
 * - Overall score circle
 * - Individual score bars
 * - Score text
 * 
 * AI RECOMMENDATION TYPES:
 * ------------------------
 * 1. "invite_to_interview" (Green, Checkmark icon)
 *    Title: "Strongly Recommend"
 *    Message: "Candidate shows strong potential and should be invited"
 *    Use when: Overall score ≥80% AND no major red flags
 * 
 * 2. "further_review" (Yellow, Warning icon)
 *    Title: "Further Review Needed"
 *    Message: "Mixed signals. Consider reviewing in detail"
 *    Use when: Overall score 60-79% OR inconsistent scores
 * 
 * 3. "reject" (Red, X icon)
 *    Title: "Not Recommended"
 *    Message: "Candidate does not meet requirements"
 *    Use when: Overall score <60% OR major concerns
 * 
 * SCORE BREAKDOWN BARS:
 * ---------------------
 * Each score (Content, Communication, Technical) shows as:
 * - Label on left
 * - Colored progress bar in middle
 * - Numeric score on right (0-100)
 * 
 * Bar fills proportionally:
 * - 80/100 → 80% width
 * - Color changes based on score (green/yellow/red)
 * - Smooth animation on load (CSS transition)
 * 
 * AI SUMMARY SECTION:
 * -------------------
 * - Paragraph text generated by GPT-4
 * - Typically 2-3 sentences
 * - Explains overall assessment
 * - Highlights main points
 * - Displayed in blue info box
 * 
 * Example summary:
 * "Strong candidate with excellent communication skills and deep
 *  technical knowledge. Demonstrated clear understanding of Python
 *  and Django frameworks. Some concerns about team leadership
 *  experience, but overall a good fit for the role."
 * 
 * STRENGTHS LIST:
 * ---------------
 * - Array of positive statements
 * - Each with green checkmark (✓)
 * - Typically 2-5 items
 * - Generated by AI from video analysis
 * 
 * Examples:
 * ✓ Excellent verbal communication
 * ✓ Deep technical knowledge of Python & Django
 * ✓ Strong problem-solving approach
 * ✓ Cultural fit with company values
 * 
 * CONCERNS LIST:
 * --------------
 * - Array of concern statements
 * - Each with warning icon (⚠)
 * - Typically 0-3 items
 * - Generated by AI from video analysis
 * 
 * Examples:
 * ⚠ Limited team leadership experience
 * ⚠ May need training on React frontend
 * ⚠ Salary expectations above budget
 * 
 * DISCLAIMER NOTE:
 * ----------------
 * "AI analysis is a tool to assist decision-making, not replace
 *  human judgment. Please review the videos yourself and consider
 *  all factors before making a final decision."
 * 
 * Purpose:
 * - Legal protection
 * - Ethical responsibility
 * - Encourages human oversight
 * - Prevents blind AI reliance
 * 
 * COLOR SCHEME:
 * -------------
 * Header: Purple to blue gradient
 * Overall score circle: Green/Yellow/Red based on score
 * Recommendation badge: Green/Yellow/Red based on type
 * Strengths: Green accents
 * Concerns: Red/Orange accents
 * Summary: Blue info box
 * 
 * RESPONSIVE DESIGN:
 * ------------------
 * - Stacks nicely on mobile (full width)
 * - Circular score stays centered
 * - Bars remain readable on small screens
 * - Text scales appropriately
 * 
 * ACCESSIBILITY:
 * --------------
 * - High contrast colors
 * - Clear visual hierarchy
 * - Icons with text labels (not icons alone)
 * - Screen reader friendly structure
 * 
 * NO API CALLS:
 * -------------
 * This is a PRESENTATIONAL component only.
 * It receives all data via props (no fetching).
 * Pure rendering based on input.
 * 
 * DATA SOURCE:
 * ------------
 * AI scores and analysis come from backend:
 * 1. Candidate submits videos
 * 2. Backend triggers AI pipeline:
 *    a. AssemblyAI transcribes videos
 *    b. GPT-4 analyzes transcripts
 *    c. GPT-4 generates scores (0-100 each)
 *    d. GPT-4 generates summary, strengths, concerns
 *    e. Backend calculates overall score (weighted average)
 *    f. Backend determines recommendation (based on scores)
 * 3. Results stored in database
 * 4. This component displays results
 * 
 * SCORING ALGORITHM (BACKEND):
 * ----------------------------
 * Overall Score = (Content × 0.4) + (Communication × 0.3) + (Technical × 0.3)
 * 
 * Example:
 * Content: 80
 * Communication: 90
 * Technical: 85
 * Overall = (80 × 0.4) + (90 × 0.3) + (85 × 0.3)
 *         = 32 + 27 + 25.5
 *         = 84.5 ≈ 85
 * 
 * CUSTOMIZATION POINTS:
 * ---------------------
 * - Change score weights (currently 40/30/30)
 * - Modify letter grade thresholds
 * - Add more score categories (e.g., "Culture Fit")
 * - Change color scheme
 * - Add export to PDF feature
 * 
 * TESTING CHECKLIST:
 * ------------------
 * [ ] Displays correct overall score
 * [ ] Shows correct letter grade
 * [ ] Score bars fill correctly
 * [ ] Recommendation badge shows correct type
 * [ ] Strengths list displays
 * [ ] Concerns list displays
 * [ ] Summary text readable
 * [ ] Disclaimer shows
 * [ ] Colors match score ranges
 * [ ] Responsive on mobile
 * 
 * FUTURE ENHANCEMENTS:
 * --------------------
 * - Export report card as PDF
 * - Email report card to hiring manager
 * - Compare multiple candidates side-by-side
 * - Historical score tracking (candidate improvement)
 * - Custom scoring weights per company
 * 
 * ════════════════════════════════════════════════════════════════════════════════
 */

import React from 'react';
import { TrendingUp, CheckCircle, AlertTriangle, XCircle, Sparkles } from 'lucide-react';

interface AIReportCardProps {
  overallScore: number;
  contentScore: number;
  communicationScore: number;
  technicalScore: number;
  aiSummary: string;
  recommendation: 'invite_to_interview' | 'further_review' | 'reject';
  strengths: string[];
  concerns: string[];
}

export default function AIReportCard({
  overallScore,
  contentScore,
  communicationScore,
  technicalScore,
  aiSummary,
  recommendation,
  strengths,
  concerns
}: AIReportCardProps) {

  const getOverallGrade = (score: number): { grade: string; color: string; bgColor: string } => {
    if (score >= 90) return { grade: 'A+', color: 'text-green-600', bgColor: 'bg-green-50' };
    if (score >= 80) return { grade: 'A', color: 'text-green-600', bgColor: 'bg-green-50' };
    if (score >= 70) return { grade: 'B', color: 'text-blue-600', bgColor: 'bg-blue-50' };
    if (score >= 60) return { grade: 'C', color: 'text-yellow-600', bgColor: 'bg-yellow-50' };
    if (score >= 50) return { grade: 'D', color: 'text-orange-600', bgColor: 'bg-orange-50' };
    return { grade: 'F', color: 'text-red-600', bgColor: 'bg-red-50' };
  };

  const getRecommendationConfig = () => {
    switch (recommendation) {
      case 'invite_to_interview':
        return {
          icon: <CheckCircle className="w-6 h-6" />,
          color: 'bg-green-500',
          bgColor: 'bg-green-50',
          textColor: 'text-green-800',
          borderColor: 'border-green-200',
          title: 'Strongly Recommend',
          message: 'This candidate shows strong potential and should be invited to interview.'
        };
      case 'further_review':
        return {
          icon: <AlertTriangle className="w-6 h-6" />,
          color: 'bg-yellow-500',
          bgColor: 'bg-yellow-50',
          textColor: 'text-yellow-800',
          borderColor: 'border-yellow-200',
          title: 'Further Review Needed',
          message: 'Mixed signals. Consider reviewing in detail before making a decision.'
        };
      case 'reject':
        return {
          icon: <XCircle className="w-6 h-6" />,
          color: 'bg-red-500',
          bgColor: 'bg-red-50',
          textColor: 'text-red-800',
          borderColor: 'border-red-200',
          title: 'Not Recommended',
          message: 'Candidate does not meet the requirements for this position.'
        };
    }
  };

  const overallGrade = getOverallGrade(overallScore);
  const recommendationConfig = getRecommendationConfig();

  return (
    <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-blue-600 p-6 text-white">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-5 h-5" />
          <h3 className="text-xl font-bold">AI Analysis Report</h3>
        </div>
        <p className="text-purple-100 text-sm">
          Generated by RecruitPro SA's AI screening engine
        </p>
      </div>

      <div className="p-6 space-y-6">

        {/* Overall Score */}
        <div className="text-center pb-6 border-b border-gray-200">
          <div className="text-sm font-semibold text-gray-600 mb-3">Overall Assessment</div>
          <div className={`inline-flex items-center justify-center w-32 h-32 rounded-full ${overallGrade.bgColor} mb-3`}>
            <div className="text-center">
              <div className={`text-5xl font-bold ${overallGrade.color}`}>
                {overallScore}
              </div>
              <div className={`text-2xl font-bold ${overallGrade.color}`}>
                {overallGrade.grade}
              </div>
            </div>
          </div>
          <p className="text-sm text-gray-600">out of 100</p>
        </div>

        {/* Score Breakdown */}
        <div>
          <h4 className="font-bold text-gray-900 mb-4">Score Breakdown</h4>
          <div className="space-y-3">
            <ScoreBar label="Content Quality" score={contentScore} />
            <ScoreBar label="Communication Skills" score={communicationScore} />
            <ScoreBar label="Technical Depth" score={technicalScore} />
          </div>
        </div>

        {/* AI Recommendation */}
        <div className={`border-2 ${recommendationConfig.borderColor} rounded-lg overflow-hidden`}>
          <div className={`${recommendationConfig.bgColor} p-4`}>
            <div className="flex items-center gap-3">
              <div className={`${recommendationConfig.color} p-2 rounded-full text-white`}>
                {recommendationConfig.icon}
              </div>
              <div>
                <div className={`font-bold ${recommendationConfig.textColor}`}>
                  {recommendationConfig.title}
                </div>
                <div className={`text-sm ${recommendationConfig.textColor}`}>
                  {recommendationConfig.message}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* AI Summary */}
        <div>
          <h4 className="font-bold text-gray-900 mb-3 flex items-center">
            <TrendingUp className="w-5 h-5 mr-2 text-blue-600" />
            AI Summary
          </h4>
          <p className="text-sm text-gray-700 leading-relaxed bg-blue-50 p-4 rounded-lg">
            {aiSummary}
          </p>
        </div>

        {/* Strengths */}
        {strengths && strengths.length > 0 && (
          <div>
            <h4 className="font-bold text-green-900 mb-3 flex items-center">
              <CheckCircle className="w-5 h-5 mr-2 text-green-600" />
              Key Strengths
            </h4>
            <ul className="space-y-2">
              {strengths.map((strength, index) => (
                <li key={index} className="flex items-start text-sm">
                  <span className="text-green-500 mr-2">✓</span>
                  <span className="text-gray-700">{strength}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Concerns */}
        {concerns && concerns.length > 0 && (
          <div>
            <h4 className="font-bold text-red-900 mb-3 flex items-center">
              <AlertTriangle className="w-5 h-5 mr-2 text-red-600" />
              Areas of Concern
            </h4>
            <ul className="space-y-2">
              {concerns.map((concern, index) => (
                <li key={index} className="flex items-start text-sm">
                  <span className="text-red-500 mr-2">⚠</span>
                  <span className="text-gray-700">{concern}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Disclaimer */}
        <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 text-xs text-gray-600">
          <strong>Note:</strong> AI analysis is a tool to assist decision-making, not replace human judgment. 
          Please review the videos yourself and consider all factors before making a final decision.
        </div>
      </div>
    </div>
  );
}

// Score Bar Component
function ScoreBar({ label, score }: { label: string; score: number }) {
  const getBarColor = (score: number): string => {
    if (score >= 80) return 'bg-green-500';
    if (score >= 60) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const getTextColor = (score: number): string => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-2">
        <span className="text-sm font-semibold text-gray-700">{label}</span>
        <span className={`text-sm font-bold ${getTextColor(score)}`}>
          {score}/100
        </span>
      </div>
      <div className="w-full bg-gray-200 rounded-full h-3 overflow-hidden">
        <div
          className={`h-3 rounded-full transition-all duration-500 ${getBarColor(score)}`}
          style={{ width: `${score}%` }}
        />
      </div>
    </div>
  );
}
