"""Add Enhanced Profile fields

Revision ID: 02400aa163dc
Revises: 770be99f0b94
Create Date: 2026-04-09 17:00:11.899479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02400aa163dc'
down_revision = '770be99f0b94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_user_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('viewer_company', sa.String(length=255), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_views_profile_user_id'), 'profile_views', ['profile_user_id'], unique=False)
    op.create_index(op.f('ix_profile_views_viewed_at'), 'profile_views', ['viewed_at'], unique=False)
    op.add_column('users', sa.Column('profile_photo', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('professional_summary', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_views_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_completion_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completion_percentage')
    op.drop_column('users', 'profile_views_count')
    op.drop_column('users', 'professional_summary')
    op.drop_column('users', 'profile_photo')
    op.drop_index(op.f('ix_profile_views_viewed_at'), table_name='profile_views')
    op.drop_index(op.f('ix_profile_views_profile_user_id'), table_name='profile_views')
    op.drop_table('profile_views')
    # ### end Alembic commands ###
