"""add_position_department_to_users

Revision ID: 03621b407d4b
Revises: b2c3d4e5f6a7
Create Date: 2026-05-31 19:30:48.087271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03621b407d4b'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
