"""add_invitation_token_to_users

Revision ID: 303ab8747c00
Revises: 03621b407d4b
Create Date: 2026-06-01 15:58:23.409324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303ab8747c00'
down_revision = '03621b407d4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invitation_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_invitation_token'), 'users', ['invitation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invitation_token'), table_name='users')
    op.drop_column('users', 'invitation_expires_at')
    op.drop_column('users', 'invitation_token')
    # ### end Alembic commands ###
