"""Add enhanced company fields

Revision ID: 3b2c4c17d14e
Revises: 02400aa163dc
Create Date: 2026-04-10 15:28:38.504908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2c4c17d14e'
down_revision = '02400aa163dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profile_views_company_id'), 'company_profile_views', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_profile_views_viewed_at'), 'company_profile_views', ['viewed_at'], unique=False)
    op.create_table('job_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('viewer_user_id', sa.UUID(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_views_job_id'), 'job_views', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_views_viewed_at'), 'job_views', ['viewed_at'], unique=False)
    op.add_column('client_companies', sa.Column('profile_views_count', sa.Integer(), nullable=True))
    op.add_column('client_companies', sa.Column('profile_completion_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_companies', 'profile_completion_percentage')
    op.drop_column('client_companies', 'profile_views_count')
    op.drop_index(op.f('ix_job_views_viewed_at'), table_name='job_views')
    op.drop_index(op.f('ix_job_views_job_id'), table_name='job_views')
    op.drop_table('job_views')
    op.drop_index(op.f('ix_company_profile_views_viewed_at'), table_name='company_profile_views')
    op.drop_index(op.f('ix_company_profile_views_company_id'), table_name='company_profile_views')
    op.drop_table('company_profile_views')
    # ### end Alembic commands ###
