"""add_indeed_posting_fields

Revision ID: 770be99f0b94
Revises: f54114dfb9bc
Create Date: 2026-04-02 11:17:55.668753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770be99f0b94'
down_revision = 'f54114dfb9bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('post_to_indeed', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('indeed_job_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'indeed_job_id')
    op.drop_column('jobs', 'post_to_indeed')
    # ### end Alembic commands ###
