"""initial_schema_unified

Revision ID: 814251e1731a
Revises: 
Create Date: 2026-03-21 14:57:13.914088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '814251e1731a'
down_revision = None
branch_labels = None
depends_on = None


def create_enum_if_not_exists(name, values):
    values_str = ", ".join([f"'{v}'" for v in values])
    try:
        op.execute(f"DO $$ BEGIN CREATE TYPE {name} AS ENUM ({values_str}); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    except Exception:
        pass

def upgrade() -> None:
    try:
        # Safely create all ENUMs first
        create_enum_if_not_exists('subscriptiontier', ['LITE', 'STANDARD', 'PREMIUM'])
        create_enum_if_not_exists('userrole', ['SUPER_ADMIN', 'AGENCY_ADMIN', 'RECRUITER', 'VIEWER'])
        create_enum_if_not_exists('candidatestatus', ['ACTIVE', 'PASSIVE', 'PLACED', 'NOT_INTERESTED', 'BLACKLISTED'])
        create_enum_if_not_exists('candidatesource', ['DIRECT_APPLICATION', 'REFERRAL', 'LINKEDIN', 'PNET', 'CAREER_JUNCTION', 'HEADHUNTED', 'WALK_IN', 'OTHER'])
        create_enum_if_not_exists('experiencelevel', ['ENTRY_LEVEL', 'MID_LEVEL', 'SENIOR_LEVEL', 'EXECUTIVE'])
        create_enum_if_not_exists('employmenttype', ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', 'FREELANCE'])
        create_enum_if_not_exists('jobstatus', ['DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'FILLED', 'EXPIRED'])
        create_enum_if_not_exists('applicationstatus', ['APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'OFFER_PENDING', 'OFFER_MADE', 'OFFER_ACCEPTED', 'HIRED', 'REJECTED', 'WITHDRAWN'])
        create_enum_if_not_exists('applicationsource', ['DIRECT_APPLY', 'RECRUITER_ADDED', 'REFERRAL', 'HEADHUNTED', 'IMPORTED'])
        create_enum_if_not_exists('rejectionreason', ['QUALIFICATIONS', 'EXPERIENCE', 'SALARY', 'LOCATION', 'CULTURE_FIT', 'BETTER_CANDIDATE', 'POSITION_FILLED', 'OTHER'])

        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('agencies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('registration_number', sa.String(length=100), nullable=True),
        sa.Column('vat_number', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('address_line1', sa.String(length=255), nullable=True),
        sa.Column('address_line2', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('province', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('subscription_tier', sa.Enum('LITE', 'STANDARD', 'PREMIUM', name='subscriptiontier', create_type=False), nullable=False),
        sa.Column('max_users', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_trial', sa.Boolean(), nullable=False),
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('subscription_starts_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('billing_email', sa.String(length=255), nullable=True),
        sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agencies_name'), 'agencies', ['name'], unique=False)
        op.create_table('client_companies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('company_size', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('contact_name', sa.String(length=255), nullable=True),
        sa.Column('contact_email', sa.String(length=255), nullable=True),
        sa.Column('contact_phone', sa.String(length=50), nullable=True),
        sa.Column('contact_position', sa.String(length=100), nullable=True),
        sa.Column('address_line1', sa.String(length=255), nullable=True),
        sa.Column('address_line2', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('province', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('registration_number', sa.String(length=100), nullable=True),
        sa.Column('vat_number', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_client_companies_agency_id'), 'client_companies', ['agency_id'], unique=False)
        op.create_index(op.f('ix_client_companies_name'), 'client_companies', ['name'], unique=False)
        op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('role', sa.Enum('SUPER_ADMIN', 'AGENCY_ADMIN', 'RECRUITER', 'VIEWER', name='userrole', create_type=False), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login_ip', sa.String(length=45), nullable=True),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_table('activities',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.UUID(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('activity_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('candidates',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('added_by', sa.UUID(), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('alternative_phone', sa.String(length=50), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('province', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('is_willing_to_relocate', sa.Boolean(), nullable=True),
        sa.Column('current_job_title', sa.String(length=255), nullable=True),
        sa.Column('current_company', sa.String(length=255), nullable=True),
        sa.Column('years_of_experience', sa.Integer(), nullable=True),
        sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('education_level', sa.String(length=100), nullable=True),
        sa.Column('education_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('certifications', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('employment_type_preference', sa.String(length=50), nullable=True),
        sa.Column('notice_period_days', sa.Integer(), nullable=True),
        sa.Column('current_salary', sa.Integer(), nullable=True),
        sa.Column('expected_salary_min', sa.Integer(), nullable=True),
        sa.Column('expected_salary_max', sa.Integer(), nullable=True),
        sa.Column('salary_currency', sa.String(length=10), nullable=True),
        sa.Column('resume_filename', sa.String(length=255), nullable=True),
        sa.Column('resume_url', sa.String(length=500), nullable=True),
        sa.Column('resume_text', sa.Text(), nullable=True),
        sa.Column('resume_parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('linkedin_url', sa.String(length=255), nullable=True),
        sa.Column('portfolio_url', sa.String(length=255), nullable=True),
        sa.Column('github_url', sa.String(length=255), nullable=True),
        sa.Column('status', sa.Enum('ACTIVE', 'PASSIVE', 'PLACED', 'NOT_INTERESTED', 'BLACKLISTED', name='candidatestatus', create_type=False), nullable=False),
        sa.Column('source', sa.Enum('DIRECT_APPLICATION', 'REFERRAL', 'LINKEDIN', 'PNET', 'CAREER_JUNCTION', 'HEADHUNTED', 'WALK_IN', 'OTHER', name='candidatesource', create_type=False), nullable=True),
        sa.Column('source_details', sa.String(length=255), nullable=True),
        sa.Column('is_immediately_available', sa.Boolean(), nullable=True),
        sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
        sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('consent_ip', sa.String(length=45), nullable=True),
        sa.Column('gdpr_consent', sa.Boolean(), nullable=True),
        sa.Column('applications_count', sa.Integer(), nullable=True),
        sa.Column('interviews_count', sa.Integer(), nullable=True),
        sa.Column('placements_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_candidates_agency_status', 'candidates', ['agency_id', 'status'], unique=False)
        op.create_index('idx_candidates_email_lower', 'candidates', [sa.literal_column('lower(email)')], unique=False)
        op.create_index('idx_candidates_skills', 'candidates', ['skills'], unique=False, postgresql_using='gin')
        op.create_index('idx_candidates_tags', 'candidates', ['tags'], unique=False, postgresql_using='gin')
        op.create_index(op.f('ix_candidates_agency_id'), 'candidates', ['agency_id'], unique=False)
        op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
        op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
        op.create_table('jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('client_company_id', sa.UUID(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('reference', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('requirements', sa.Text(), nullable=True),
        sa.Column('responsibilities', sa.Text(), nullable=True),
        sa.Column('benefits', sa.Text(), nullable=True),
        sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('years_of_experience_min', sa.Integer(), nullable=True),
        sa.Column('years_of_experience_max', sa.Integer(), nullable=True),
        sa.Column('experience_level', sa.Enum('ENTRY_LEVEL', 'MID_LEVEL', 'SENIOR_LEVEL', 'EXECUTIVE', name='experiencelevel', create_type=False), nullable=True),
        sa.Column('education_level', sa.String(length=100), nullable=True),
        sa.Column('certifications', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('province', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('is_remote', sa.Boolean(), nullable=True),
        sa.Column('remote_type', sa.String(length=50), nullable=True),
        sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', 'FREELANCE', name='employmenttype', create_type=False), nullable=False),
        sa.Column('salary_min', sa.Integer(), nullable=True),
        sa.Column('salary_max', sa.Integer(), nullable=True),
        sa.Column('salary_currency', sa.String(length=10), nullable=True),
        sa.Column('salary_period', sa.String(length=20), nullable=True),
        sa.Column('show_salary', sa.Boolean(), nullable=True),
        sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('closing_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'FILLED', 'EXPIRED', name='jobstatus', create_type=False), nullable=False),
        sa.Column('is_urgent', sa.Boolean(), nullable=True),
        sa.Column('is_featured', sa.Boolean(), nullable=True),
        sa.Column('post_to_pnet', sa.Boolean(), nullable=True),
        sa.Column('post_to_careerjunction', sa.Boolean(), nullable=True),
        sa.Column('post_to_linkedin', sa.Boolean(), nullable=True),
        sa.Column('pnet_job_id', sa.String(length=100), nullable=True),
        sa.Column('careerjunction_job_id', sa.String(length=100), nullable=True),
        sa.Column('linkedin_job_id', sa.String(length=100), nullable=True),
        sa.Column('views_count', sa.Integer(), nullable=True),
        sa.Column('applications_count', sa.Integer(), nullable=True),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_jobs_agency_status', 'jobs', ['agency_id', 'status'], unique=False)
        op.create_index('idx_jobs_search', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
        op.create_index('idx_jobs_skills', 'jobs', ['skills'], unique=False, postgresql_using='gin')
        op.create_index(op.f('ix_jobs_agency_id'), 'jobs', ['agency_id'], unique=False)
        op.create_index(op.f('ix_jobs_reference'), 'jobs', ['reference'], unique=True)
        op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
        op.create_table('applications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agency_id', sa.UUID(), nullable=False),
        sa.Column('job_id', sa.UUID(), nullable=False),
        sa.Column('candidate_id', sa.UUID(), nullable=False),
        sa.Column('client_company_id', sa.UUID(), nullable=True),
        sa.Column('assigned_to', sa.UUID(), nullable=True),
        sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'INTERVIEWED', 'OFFER_PENDING', 'OFFER_MADE', 'OFFER_ACCEPTED', 'HIRED', 'REJECTED', 'WITHDRAWN', name='applicationstatus', create_type=False), nullable=False),
        sa.Column('source', sa.Enum('DIRECT_APPLY', 'RECRUITER_ADDED', 'REFERRAL', 'HEADHUNTED', 'IMPORTED', name='applicationsource', create_type=False), nullable=True),
        sa.Column('cover_letter', sa.Text(), nullable=True),
        sa.Column('resume_version', sa.String(length=255), nullable=True),
        sa.Column('screening_score', sa.Integer(), nullable=True),
        sa.Column('screening_notes', sa.Text(), nullable=True),
        sa.Column('screening_passed', sa.Boolean(), nullable=True),
        sa.Column('screened_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('screened_by', sa.UUID(), nullable=True),
        sa.Column('interview_scheduled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('interview_completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('interview_feedback', sa.Text(), nullable=True),
        sa.Column('interview_rating', sa.Integer(), nullable=True),
        sa.Column('offer_amount', sa.Integer(), nullable=True),
        sa.Column('offer_currency', sa.String(length=10), nullable=True),
        sa.Column('offer_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('offer_accepted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('offer_rejected_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('rejection_reason', sa.Enum('QUALIFICATIONS', 'EXPERIENCE', 'SALARY', 'LOCATION', 'CULTURE_FIT', 'BETTER_CANDIDATE', 'POSITION_FILLED', 'OTHER', name='rejectionreason', create_type=False), nullable=True),
        sa.Column('rejection_notes', sa.Text(), nullable=True),
        sa.Column('rejected_by', sa.UUID(), nullable=True),
        sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('withdrawal_reason', sa.Text(), nullable=True),
        sa.Column('match_score', sa.Integer(), nullable=True),
        sa.Column('match_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('communication_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['client_company_id'], ['client_companies.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['screened_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_applications_agency_status', 'applications', ['agency_id', 'status'], unique=False)
        op.create_index('idx_applications_candidate_status', 'applications', ['candidate_id', 'status'], unique=False)
        op.create_index('idx_applications_job_status', 'applications', ['job_id', 'status'], unique=False)
        op.create_index('idx_applications_unique', 'applications', ['candidate_id', 'job_id'], unique=True)
        op.create_index(op.f('ix_applications_agency_id'), 'applications', ['agency_id'], unique=False)
        op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
        op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
        op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
        # ### end Alembic commands ###
    except Exception:
        pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_agency_id'), table_name='applications')
    op.drop_index('idx_applications_unique', table_name='applications')
    op.drop_index('idx_applications_job_status', table_name='applications')
    op.drop_index('idx_applications_candidate_status', table_name='applications')
    op.drop_index('idx_applications_agency_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_reference'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_agency_id'), table_name='jobs')
    op.drop_index('idx_jobs_skills', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_search', table_name='jobs', postgresql_using='gin')
    op.drop_index('idx_jobs_agency_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_agency_id'), table_name='candidates')
    op.drop_index('idx_candidates_tags', table_name='candidates', postgresql_using='gin')
    op.drop_index('idx_candidates_skills', table_name='candidates', postgresql_using='gin')
    op.drop_index('idx_candidates_email_lower', table_name='candidates')
    op.drop_index('idx_candidates_agency_status', table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_client_companies_name'), table_name='client_companies')
    op.drop_index(op.f('ix_client_companies_agency_id'), table_name='client_companies')
    op.drop_table('client_companies')
    op.drop_index(op.f('ix_agencies_name'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
