"""Add category and positions_available to jobs

Revision ID: 9ed0ffc5b62d
Revises: 3b2c4c17d14e
Create Date: 2026-04-16 22:28:58.647452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed0ffc5b62d'
down_revision = '3b2c4c17d14e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plan_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('cv_parses_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_match_calculations_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_search_queries_per_month', sa.Integer(), nullable=True),
    sa.Column('price_zar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plan_limits_plan_name'), 'subscription_plan_limits', ['plan_name'], unique=True)
    op.create_table('company_usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('cv_parses_used', sa.Integer(), nullable=True),
    sa.Column('ai_match_calculations_used', sa.Integer(), nullable=True),
    sa.Column('ai_search_queries_used', sa.Integer(), nullable=True),
    sa.Column('estimated_ai_cost_zar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_operation_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_usage_tracking_agency_id'), 'company_usage_tracking', ['agency_id'], unique=False)
    op.create_table('usage_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_alerts_agency_id'), 'usage_alerts', ['agency_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_zar', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_agency_id'), 'usage_logs', ['agency_id'], unique=False)
    op.add_column('jobs', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('jobs', sa.Column('qualifications', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('jobs', sa.Column('positions_available', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'requirements',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="CASE WHEN requirements IS NOT NULL THEN ARRAY[requirements] ELSE ARRAY[]::VARCHAR[] END")
    op.alter_column('jobs', 'responsibilities',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="CASE WHEN responsibilities IS NOT NULL THEN ARRAY[responsibilities] ELSE ARRAY[]::VARCHAR[] END")
    op.alter_column('jobs', 'benefits',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="CASE WHEN benefits IS NOT NULL THEN ARRAY[benefits] ELSE ARRAY[]::VARCHAR[] END")
    op.create_index(op.f('ix_jobs_category'), 'jobs', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_category'), table_name='jobs')
    op.alter_column('jobs', 'benefits',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'responsibilities',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'requirements',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('jobs', 'positions_available')
    op.drop_column('jobs', 'qualifications')
    op.drop_column('jobs', 'category')
    op.drop_index(op.f('ix_usage_logs_agency_id'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_usage_alerts_agency_id'), table_name='usage_alerts')
    op.drop_table('usage_alerts')
    op.drop_index(op.f('ix_company_usage_tracking_agency_id'), table_name='company_usage_tracking')
    op.drop_table('company_usage_tracking')
    op.drop_index(op.f('ix_subscription_plan_limits_plan_name'), table_name='subscription_plan_limits')
    op.drop_table('subscription_plan_limits')
    # ### end Alembic commands ###
