"""add notification preferences

Revision ID: b01f94574311
Revises: f88b956168b6
Create Date: 2026-05-21 16:07:51.007818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01f94574311'
down_revision = 'f88b956168b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inapp_new_application', sa.Boolean(), nullable=True),
    sa.Column('inapp_application_status', sa.Boolean(), nullable=True),
    sa.Column('inapp_ai_match', sa.Boolean(), nullable=True),
    sa.Column('inapp_interview', sa.Boolean(), nullable=True),
    sa.Column('inapp_offer', sa.Boolean(), nullable=True),
    sa.Column('inapp_billing', sa.Boolean(), nullable=True),
    sa.Column('inapp_system', sa.Boolean(), nullable=True),
    sa.Column('email_new_application', sa.Boolean(), nullable=True),
    sa.Column('email_application_status', sa.Boolean(), nullable=True),
    sa.Column('email_ai_match', sa.Boolean(), nullable=True),
    sa.Column('email_interview', sa.Boolean(), nullable=True),
    sa.Column('email_offer', sa.Boolean(), nullable=True),
    sa.Column('email_billing', sa.Boolean(), nullable=True),
    sa.Column('email_system', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('message_templates', 'agency_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_message_templates_agency_id'), 'message_templates', ['agency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_templates_agency_id'), table_name='message_templates')
    op.alter_column('message_templates', 'agency_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
