"""add_integration_tables

Revision ID: de0ee8eb24cd
Revises: 002_add_user_roles
Create Date: 2026-04-02 10:57:24.932414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de0ee8eb24cd'
down_revision = '002_add_user_roles'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'platform', name='uix_company_platform')
    )
    op.create_index('idx_integration_connections_company', 'integration_connections', ['company_id'], unique=False)
    op.create_table('job_platform_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_job_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('applications_count', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'platform', name='uix_job_platform')
    )
    op.create_index('idx_job_platform_postings_job', 'job_platform_postings', ['job_id'], unique=False)
    op.create_index('idx_job_platform_postings_platform', 'job_platform_postings', ['platform'], unique=False)
    op.add_column('applications', sa.Column('external_application_id', sa.String(length=255), nullable=True))
    op.add_column('applications', sa.Column('source_url', sa.Text(), nullable=True))
    op.alter_column('jobs', 'experience_level',
               existing_type=postgresql.ENUM('entry_level', 'mid_level', 'senior_level', 'executive', name='experiencelevel'),
               nullable=False)
    op.drop_index(op.f('idx_jobs_agency_status'), table_name='jobs')
    op.drop_index(op.f('idx_jobs_search'), table_name='jobs', postgresql_using='gin')
    op.drop_index(op.f('idx_jobs_skills'), table_name='jobs', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_jobs_skills'), 'jobs', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_jobs_search'), 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_jobs_agency_status'), 'jobs', ['agency_id', 'status'], unique=False)
    op.alter_column('jobs', 'experience_level',
               existing_type=postgresql.ENUM('entry_level', 'mid_level', 'senior_level', 'executive', name='experiencelevel'),
               nullable=True)
    op.drop_column('applications', 'source_url')
    op.drop_column('applications', 'external_application_id')
    op.drop_index('idx_job_platform_postings_platform', table_name='job_platform_postings')
    op.drop_index('idx_job_platform_postings_job', table_name='job_platform_postings')
    op.drop_table('job_platform_postings')
    op.drop_index('idx_integration_connections_company', table_name='integration_connections')
    op.drop_table('integration_connections')
    # ### end Alembic commands ###
