"""add_summary_and_work_history_to_candidate

Revision ID: ef46b50a58bd
Revises: a1b2c3d4e5f6
Create Date: 2026-05-22 17:19:08.272913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef46b50a58bd'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('career_pages_company_id_key'), 'career_pages', type_='unique')
    op.drop_constraint(op.f('career_pages_slug_key'), 'career_pages', type_='unique')
    op.drop_index(op.f('ix_career_pages_company_id'), table_name='career_pages')
    op.create_index(op.f('ix_career_pages_company_id'), 'career_pages', ['company_id'], unique=True)
    op.drop_index(op.f('ix_career_pages_slug'), table_name='career_pages')
    op.create_index(op.f('ix_career_pages_slug'), 'career_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_email_sequence_enrollments_application_id'), 'email_sequence_enrollments', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_scorecards_scored_by'), 'interview_scorecards', ['scored_by'], unique=False)
    op.alter_column('job_alerts', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'daily'::character varying"))
    op.drop_constraint(op.f('onboarding_checklists_application_id_key'), 'onboarding_checklists', type_='unique')
    op.drop_index(op.f('ix_onboarding_checklists_application_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_onboarding_checklists_application_id'), 'onboarding_checklists', ['application_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_checklists_application_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_onboarding_checklists_application_id'), 'onboarding_checklists', ['application_id'], unique=False)
    op.create_unique_constraint(op.f('onboarding_checklists_application_id_key'), 'onboarding_checklists', ['application_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('job_alerts', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'daily'::character varying"))
    op.drop_index(op.f('ix_interview_scorecards_scored_by'), table_name='interview_scorecards')
    op.drop_index(op.f('ix_email_sequence_enrollments_application_id'), table_name='email_sequence_enrollments')
    op.drop_index(op.f('ix_career_pages_slug'), table_name='career_pages')
    op.create_index(op.f('ix_career_pages_slug'), 'career_pages', ['slug'], unique=False)
    op.drop_index(op.f('ix_career_pages_company_id'), table_name='career_pages')
    op.create_index(op.f('ix_career_pages_company_id'), 'career_pages', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('career_pages_slug_key'), 'career_pages', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('career_pages_company_id_key'), 'career_pages', ['company_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('candidates', 'work_history')
    op.drop_column('candidates', 'summary')
    # ### end Alembic commands ###
