"""add_indeed_source

Revision ID: f54114dfb9bc
Revises: de0ee8eb24cd
Create Date: 2026-04-02 11:07:28.733383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54114dfb9bc'
down_revision = 'de0ee8eb24cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE applicationsource ADD VALUE IF NOT EXISTS 'indeed';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
