"""
Pydantic schemas for API requests/responses (UPDATED with Sprint 3)
"""
from app.schemas.agency import (
    AgencyBase,
    AgencyCreate,
    AgencyUpdate,
    AgencyResponse,
    AgencyBrief,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserBrief,
    PasswordChange,
)
from app.schemas.auth import (
    LoginRequest,
    LoginResponse,
    TokenResponse,
    RegisterRequest,
    RegisterResponse,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    EmailVerifyRequest,
    MessageResponse,
    CandidateRegisterRequest,
    CompanyRegisterRequest,
    UnifiedRegisterRequest,
)
from app.schemas.job import (
    JobBase,
    JobCreate,
    JobUpdate,
    JobResponse,
    JobBrief,
    JobFilter,
    JobStatusUpdate,
    JobStatistics,
    PublicJobBrief,
    PublicJobDetail,
)
from app.schemas.client_company import (
    ClientCompanyBase,
    ClientCompanyCreate,
    ClientCompanyUpdate,
    ClientCompanyResponse,
    ClientCompanyBrief,
)
from app.schemas.candidate import (
    CandidateBase,
    CandidateCreate,
    CandidateUpdate,
    CandidateResponse,
    CandidateBrief,
    CandidateFilter,
    ResumeUploadResponse,
    CandidateStatistics,
)
from app.schemas.application import (
    ApplicationBase,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationResponse,
    ApplicationBrief,
    ApplicationFilter,
    ApplicationStatusUpdate,
    ApplicationScreening,
    InterviewSchedule,
    InterviewComplete,
    OfferMake,
    OfferRespond,
    ApplicationReject,
    ApplicationWithdraw,
    ApplicationPipeline,
    ApplicationPipelineStage,
    ApplicationStatistics,
)

__all__ = [
    # Agency
    "AgencyBase",
    "AgencyCreate",
    "AgencyUpdate",
    "AgencyResponse",
    "AgencyBrief",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserBrief",
    "PasswordChange",
    # Auth
    "LoginRequest",
    "LoginResponse",
    "TokenResponse",
    "RegisterRequest",
    "RegisterResponse",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "EmailVerifyRequest",
    "MessageResponse",
    "CandidateRegisterRequest",
    "CompanyRegisterRequest",
    "UnifiedRegisterRequest",
    # Job
    "JobBase",
    "JobCreate",
    "JobUpdate",
    "JobResponse",
    "JobBrief",
    "JobFilter",
    "JobStatusUpdate",
    "JobStatistics",
    "PublicJobBrief",
    "PublicJobDetail",
    # Client Company
    "ClientCompanyBase",
    "ClientCompanyCreate",
    "ClientCompanyUpdate",
    "ClientCompanyResponse",
    "ClientCompanyBrief",
    # Candidate
    "CandidateBase",
    "CandidateCreate",
    "CandidateUpdate",
    "CandidateResponse",
    "CandidateBrief",
    "CandidateFilter",
    "ResumeUploadResponse",
    "CandidateStatistics",
    # Application
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationResponse",
    "ApplicationBrief",
    "ApplicationFilter",
    "ApplicationStatusUpdate",
    "ApplicationScreening",
    "InterviewSchedule",
    "InterviewComplete",
    "OfferMake",
    "OfferRespond",
    "ApplicationReject",
    "ApplicationWithdraw",
    "ApplicationPipeline",
    "ApplicationPipelineStage",
    "ApplicationStatistics",
]
